twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        # point this wherever your images live
        '%kernel.project_dir%/src/Shared/Infrastructure/Templates/pdf': pdf

when@test:
    twig:
        strict_variables: true
